### ISSUE TITLE
How to run scripts

### ISSUE THREAD

**Issue by fountainhead** [o2platform/nwr#34]
Hi, I just came across this project and unable to figure out how to use this project.

I want to run the sample script mentioned, https://gist.github.com/DinisCruz/516417b0e70a2ba5e8bb#file-91-multiple-google-searches-js

I installed `nwr` using `sudo npm install nwr -g`.

How do I run the script? `node  91-multiple-google-searches-js` does not work.

Sorry for the basic question!

**Comment by DinisCruz** [comment]
No worries, that is not at all a basic question (since I kinda droped a bit crome-driver support for this version (and have not update the docs))

Here is how you get it to work

```sh
git clone git@github.com:o2platform/nwr.git
cd nwr
npm install
```
![image](https://cloud.githubusercontent.com/assets/656739/5814418/1e158f4c-a083-11e4-9997-d044189d5667.png)

...

![image](https://cloud.githubusercontent.com/assets/656739/5814413/1065d686-a083-11e4-8da8-69596b79c248.png)

The command to run the version with selenium/chrome-driver support is:

```sh
coffee src/selenium/app.coffee
```

if on first run you get
![image](https://cloud.githubusercontent.com/assets/656739/5814400/edd7d380-a082-11e4-9fce-2ffea9a1e7e0.png)
...
![image](https://cloud.githubusercontent.com/assets/656739/5814404/f882f3f0-a082-11e4-81d3-b95947e985ea.png)

is because you need to do this (from the README)

> as per documented at https://github.com/rogerwang/node-webkit/wiki/Chromedriver you need to 
> download the chrome driver for your platform from http://dl.node-webkit.org/v0.11.2/ and copy it into 
> the ./node_modules/nodewebkit/nodewebkit folder.

> In OSx the file to download is the chromedriver-nw-v0.11.2-osx-x64 and you can open the folder to 
> copy the unziped file using open ./node_modules/nodewebkit/nodewebkit

for example with:

```sh
cd node_modules/nodewebkit/nodewebkit/
curl -O http://dl.nwjs.io/v0.11.2/chromedriver-nw-v0.11.2-osx-x64.zip
unzip chromedriver-nw-v0.11.2-osx-x64.zip
mv chromedriver-nw-v0.11.2-osx-x64/chromedriver .
ls
```

![image](https://cloud.githubusercontent.com/assets/656739/5814519/2d0352f4-a084-11e4-8c42-bc521bef976e.png)

now it should be a case of

```sh
cd ../../..
coffee src/selenium/app.coffee
```

which should look like this:

![image](https://cloud.githubusercontent.com/assets/656739/5814523/439c6c26-a084-11e4-9f7e-6214d3eebf29.png)

If all went well you should see something like this (with the console log messages confirming that the WebDriver was driving the requests)

![image](https://cloud.githubusercontent.com/assets/656739/5814541/7c89009e-a084-11e4-8691-394c4d40c36b.png)


The script that is shown by default already the main thing that you get from that gist you linked

```coffee
text = "o2platform node-webkit-repl"
browser.eval "window.location.href='http://www.google.com'", ()->
    browser.elementByName 'q', (err, element)->
        element.clear ->
            element.sendKeys text, nop
            browser.elementByName 'btnG', (err, button) ->
                button.click(text)

value = 'The answer is ' + 42;
return value;
```

For reference here is the updated version of that script (in coffee script)

```coffee
# same as example 91 but written in coffee script
resetToParentFrame = (next)->
    browser._jsonWireCall
        method: 'POST' , 
        relPath: '/frame/parent' , 
        data: {} , 
        cb: next
 
select_Frame1 = (next)->
    browser.frame('iframe1', next)
 
open_Search_Google = (text, next)->
        resetToParentFrame ()->
            select_Frame1 ()->
                browser.eval "window.location='http://www.google.com'", ()->
                    browser.elementByName 'q', (err, element)->
                        element.clear () ->
                            element.sendKeys(text)
                            browser.elementByName 'btnG', (err, button)->
                                button.click(next)
 
open_Search_Google 'o2platform', ()->
    open_Search_Google 'owasp', ->
        
 
return "done"
```

Btw, the script above can sometimes lose the bottom frame (although it will still run), you can get it back by clicking on the back  button (or refreshing the window)

also if you lose a script that you were writing take a look at https://github.com/o2platform/nwr/issues/9

**Comment by DinisCruz** [comment]
Btw, I actually found much more powerful (and faster) to execute browser automation  commands directly via chrome-remote-debugger, which you can see in action if you run 

```sh 
npm run repl-gui
```

or 

```
bin/node-webkit-repl gui
```

![image](https://cloud.githubusercontent.com/assets/656739/5814700/64bfb58c-a086-11e4-8413-e461b5e3fd89.png)

In that UI you could do something like 

```
if (iframe1.contentWindow.location.href.indexOf 'google') is -1
    iframe1.src='https://www.google.com'
else
    document = iframe1.contentDocument
    document.getElementsByName('q')[0].value = 'Node WebKit REPL'
    document.getElementsByName('btnG')[0].click()
```

Here are the Node-Webkit window commands/api: https://github.com/o2platform/nwr/blob/master/src/api/NodeWebKit-Service.coffee

Here are the chrome commands/api: https://github.com/o2platform/nwr/blob/master/src/api/Remote-Chrome-API.coffee

The main use I get from this module everyday is to use it to run mocha tests which use this https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/API/QA-TM_4_0_Design.coffee to create the environment you can see at https://vimeo.com/116027788

btw there are tons of example in that repo on how to use this NWR module to drive chrome an insane speeds. See for example https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/API/Jade-API.coffee and https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/regression-sprint-1.coffee

**Comment by fountainhead** [comment]
@DinisCruz Thank you. Everything works like your described. I'll try to work with this now.
The project looks very interesting and useful. Thank you.

**Comment by DinisCruz** [comment]
cool, let me know if you have more questions (don't be afraid to open more issues, even for small things/questions, since that is a great way to document how it works).

I'm using it every day, but have not had time to update this (I did start a refactoring which you can see https://github.com/o2platform/nwr/tree/nwr-refactoring which needs more work)
